services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${TODO_PORT}:${TODO_PORT}"
    volumes:
      - ./DB:/app/DB:rw
    environment:
      DOCKER_TODO_DBFOLDER: /app/DB